name: 'Terraform GitHub Actions'
on:
  push:
    branches:
      - "main"
jobs:
  terraform-plan:
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    steps:
      - name: "Setup - Checkout"
        uses: actions/checkout@master

      - name: "Setup - Build AWS Credentials"
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials

      - name: "Setup - Terraform CLI"
        uses: hashicorp/setup-terraform@v1.3.2

      - name: "Run - Terraform Init"
        run: terraform init -input=false

      - name: "Run - Terraform Apply"
        id: apply
        run: terraform apply -auto-approve

      - name: "Run - Terraform Destroy"
        id: destroy
        run: terraform destroy -auto-approve -target module.terraform-eks-demo
